VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "salesOrderSummary"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Public shipNumber As String, shipDate As String

Public customerNumber As String, poNumber As String, poDate As String, vmOrderNumber As String

Public qty As Long

Public netTotalWeight As Double, grossTotalWeight As Double
